# example netlify.toml
[build]
  #command = "npm run start"
  functions = "lambda"
  publish = "dist"


# Branch deploy context: All deploys that are not from a pull/merge request
# or from the production branch will inherit these settings.
[context.nopgnative]
  command = "npm run start"

## (optional) Settings for Netlify Dev
## https://github.com/netlify/netlify-dev-plugin#project-detection
#[dev] 
#  command = "yarn start" # Command to start your dev server
#  port = 3000 # Port that the dev server will be listening on
#  publish = "dist" # Folder with the static content for _redirect file

## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/ 
